language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build --verbose
notifications:
  email:
    on_success: never